### ISSUE TITLE
d.ts file not generated at all?

### ISSUE THREAD

**Issue by bary12** [nadako/hxtsdgen#18]
Haxe version: 3.4.7
hxtsdgen version: 0.1.1
OS: Ubuntu 18.04 x64

main.d.ts is not generated at all (the command `find . -name "*.d.ts"` does not find anything). There is also no error and the compilation output is clean.

build.hxml

```
-cp src
-main Main
-js out/out.js
-lib hxtsdgen
```

src/Main.hx

```
package ;
@:expose
@:keep
class MyClass {
    public var test: Int;
}

class Main {
    static public function main() {
        
    }
}
```

I tried everything, including actually using `MyClass` in `Main`,  `-dce no` and I even tried reversing the order of `-lib` and `-js` but nothing worked.

**Comment by bary12** [comment]
adding
```
--macro hxtsdgen.Generator.use()
```
like in extraParams.hxml solved the problem. If this is the intended usage, it is not documented.

**Comment by elsassph** [comment]
Sorry, the haxelib was missing a file (`extraParams.hxml` as you found out) adding the build macro. I pushed a new `0.1.2` version.

The `.d.ts` should be located in the same folder where `out.js` is generated.

**Comment by bary12** [comment]
Thanks for the quick response! Works now.
