### ISSUE TITLE
typedef support

### ISSUE THREAD

**Issue by francescoagati** [nadako/hxtsdgen#3]
hi,
there is mode for add support for types export?

**Comment by back2dos** [comment]
Across all targets, typedefs don't exist at compile time. What's your use case?

**Comment by francescoagati** [comment]
imagine this type in haxe  
```
@:expose typedef Player = {name:String,surname:String}
```
in javascript with jsdoc and typescript i want to import the type player generated from haxe in the file App.d.ts
in this mode for example
```
/**
 * @param player { import("./App.d.ts").Player }
 */
function walk(player) {
    console.log(`Walking ${p.name}...`);
}
```

**Comment by fullofcaffeine** [comment]
> Across all targets, typedefs don't exist at compile time

@back2dos So that means they don't exist in the AST? So it'd be impossible to even get hold of them to generate TS type defs, it appears.

**Comment by nadako** [comment]
`typedef`s exist in AST. from them we should generate TS `interface` if it's a typedef to a structure, or `type` if it's some other type

**Comment by elsassph** [comment]
The problem is that typedefs don't have a name in the AST, isn't it?

**Comment by nadako** [comment]
They do, that's their purpose - to give a name to a type :)

It's here https://github.com/nadako/hxtsdgen/blob/8244c170445c7f763045f2eca18a1b77beab8688/src/hxtsdgen/TypeRenderer.hx#L69

**Comment by elsassph** [comment]
Typedefs are now supported \o/

**Comment by francescoagati** [comment]
sorry for late response @elsassph  now i have tested the typedef support in a big project. and all work really good
thanks
