### ISSUE TITLE
Classes being included twice?

### ISSUE THREAD

**Issue by jcward** [nadako/hxtsdgen#34]
Just FYI - I'm not sure I'm really using the project as intended, but whatever I was doing (I think perhaps the class was being auto-included, and also specifically included?), I was seeing class definitions appearing twice. I patched it by setting an entry in the `autoIncluded` map here:

https://github.com/jcward/hxtsdgen/commit/6f8287f21266135ee54173b9aa893c0c1f9e55a7#diff-367f0d832fe6b37ad181eb1bef309a64R44

... although I also changed the name of the map from `autoIncluded` to `isIncluded`, as I assumed the intent of the map was to avoid duplicates, so it doesn't really matter whether it was included via auto or not.

**Comment by singpolyma** [comment]
I am seeing this bug also

**Comment by elsassph** [comment]
Thanks for your comments/interest @singpolyma - this tool is unfortunately unmaintained.

**Comment by singpolyma** [comment]
For anyone else who finds this, I think this https://github.com/singpolyma/hxtsdgen/commit/58561a7d28d3335f917983c3d1d5ef39b37e7a19 is a more correct fix
