### ISSUE TITLE
strange error on haxe 4

### ISSUE THREAD

**Issue by francescoagati** [nadako/hxtsdgen#4]
hi,
i am try to compile this lib with haxe 4 rc 1.
but i have this error
`src/hxtsdgen/TypeRenderer.hx:49: characters 23-50 : haxe.macro.Type has no field applyTypeParameters
src/hxtsdgen/TypeRenderer.hx:68: characters 23-50 : haxe.macro.Type has no field applyTypeParameters
src/hxtsdgen/TypeRenderer.hx:81: characters 33-43 : haxe.macro.Type has no field toString
src/hxtsdgen/Generator.hx:37: characters 25-36 : haxe.macro.Type has no field follow
`
i have also added using haxe.macro.TypeTools;
bit if is like if the methods applyToParameters and follow arent applyed to type haxe.macro.Type

**Comment by francescoagati** [comment]
but only with haxe complete.hxml.
with haxe test.hxml is work

**Comment by fullofcaffeine** [comment]
@francescoagati is this still happening for you with the latest Haxe?

**Comment by elsassph** [comment]
You may want to retry with rc2.

**Comment by francescoagati** [comment]
no now it's ok

**Comment by francescoagati** [comment]
thanks
